#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#Single monitor
bspc monitor -d 1 2 3 4 5

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

bspc config border_width                1
bspc config window_gap                  5
bspc config top_padding                 30
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config single_monocle              false
bspc config click_to_focus              true
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true
bspc config pointer_motion_interval     7

# Colors
bspc config normal_border_color		"#44475a"
bspc config active_border_color		"#bd93f9"
bspc config focused_border_color	"#88c0d0"
bspc config presel_feedback_color	"#6272a4"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &
# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &
